# Built from https://github.com/rust-lang/docker-rust
# Note we specify an explicit version of the image as a workaround for the fact that
# on developer machines "latest" gets pulled once at the beginning of time then never
# updated. So unfortunately we will need to maintain the version here.
FROM rust:1.88 AS builder

# Install build dependencies
RUN apt update && apt install -y build-essential lld pkg-config libssl-dev libgmp-dev clang

WORKDIR /usr/libra
COPY . .
RUN cargo build --release

FROM ubuntu:latest
RUN apt update && apt install -y ca-certificates

COPY --from=builder /usr/libra/target/release/libra /usr/libra/target/release/libra-* /usr/local/bin/
