repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        files: \.(rs|move)$
      - id: end-of-file-fixer
        files: \.(rs|move)$
      # - id: check-added-large-files
      #   args:
      #     - --maxkb=2000
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
      -   id: fmt
      -   id: sort