name: setup
description: initialize ubuntu environment
runs:
  using: composite
  steps:

    - name: free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
        version: 1.0

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.70.0
        override: true

    - name: install rustfmt clippy
      shell: bash
      run: rustup component add rustfmt clippy

    # - name: enable sccache
    #   uses: 0o-de-lally/sccache-action@2dd73efb90f3c9113a0cab8d983df6eb2b21fd20

    - name: also rust cache
      uses: Swatinem/rust-cache@v2.7.0
      with:
        shared-key: "libra"
        cache-on-failure: "true"

    - name: export diem-node DIEM_FORGE_NODE_BIN_PATH
      shell: bash
      run: echo "DIEM_FORGE_NODE_BIN_PATH=${{github.workspace}}/diem-node" >> $GITHUB_ENV

    - name: install diem-node (for smoke tests)
      shell: bash
      run: >
        wget -O $DIEM_FORGE_NODE_BIN_PATH https://github.com/0LNetworkCommunity/diem/releases/latest/download/diem-node &&
        sudo chmod 755 $DIEM_FORGE_NODE_BIN_PATH &&
        echo $DIEM_FORGE_NODE_BIN_PATH &&
        ls -l $DIEM_FORGE_NODE_BIN_PATH
