runs:
  using: composite
  steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
        version: 1.0
    - name: checkout sources
      uses: actions/checkout@v3
      with:
        # git-restore-mtime-bare uses the ref log to find the correct timestamp
        # for each file. This requires a full git history. The default value (1)
        # creates a shallow checkout.
        fetch-depth: 0

    - name: cache rust
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "libra" # to share across CI builds, so it is not job-id specific
        cache-on-failure: true

    - name: cargo git mtime restore for cargo github dependencies
      uses: chetan/git-restore-mtime-action@v2