name: get cli bin
description: use pre-build libra-cli bin for CI
runs:
  using: composite
  steps:
    - name: export diem-node DIEM_FORGE_NODE_BIN_PATH
      shell: bash
      run: |
        echo "LIBRA_BIN=${{github.workspace}}/libra" >> $GITHUB_ENV
        echo "DIEM_FORGE_NODE_BIN_PATH=${{github.workspace}}/libra" >> $GITHUB_ENV
        # also have the file available in $PATH
        echo ${{github.workspace}} >> $GITHUB_PATH

    - name: install diem-node (for smoke tests)
      shell: bash
      run: >
        wget -O $LIBRA_BIN https://github.com/0LNetworkCommunity/libra-framework/releases/download/ci-bins/libra &&
        sudo chmod 755 $LIBRA_BIN &&
        echo $LIBRA_BIN &&
        ls -l $LIBRA_BIN
        # for debugging, display the version, and ensure using the same aliases
        ${{github.workspace}}/libra
        libra version
        $LIBRA_BIN version
        $DIEM_FORGE_NODE_BIN_PATH version
