name: ci-preheat

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, ubuntu-20.04, windows-latest ]
    name: preheat cache for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt
      - name: update cargo index
        continue-on-error: true
        run: cargo install empty-library
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev -y
      - name: install dependencies (windows only)
        if: matrix.os == 'windows-latest'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
          name: Set LIBCLANG_PATH
          run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2