name: rust ci

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
    branches: ["**"] # glob pattern to allow slash /
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release**"
      - "main**"
  schedule:
    - cron: "30 00 * * *"

env:
  DIEM_FORGE_NODE_BIN_PATH: ${{github.workspace}}/diem-node
  LIBRA_CI: 1
  MODE_0L: "TESTNET"
  LAST_COMMIT_MSG: ${{github.event.head_commit.message}}

jobs:
  upgrades:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        timeout-minutes: 5

      - name: Check out code
        uses: actions/checkout@v3
      - name: test
        run: |
          echo ${{github.event.commits[0]}}
