name: move framework tests

on:
  push:
    tags: # only on releases, not RC, since we've tested already
      - "[0-9]+.[0-9]+.[0-9]+"
    branches: ["**"] # glob pattern to allow slash /
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release**"
      - "main**"

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      #   timeout-minutes: 15

      - uses: actions/checkout@v3

      - name: fetch libra cli
        uses: ./.github/actions/get_cli

      # Move framework tests
      - name: move framework
        working-directory: ./framework/libra-framework
        run: $LIBRA_BIN move test
