name: ci-preheat

on:
  workflow_call:
jobs:
  heat:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        uses: 0o-de-lally/libra-v7/.github/actions/build_env@ci

      - name: build query
        run: cargo b