name: ci-preheat

on:
  workflow_call:
jobs:
  heat:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup env
        uses: ./.github/workflows/env.yaml

      - name: build query
        run: cargo b -p libra-query