name: ci-preheat

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  publish:
    strategy:
      fail-fast: true
    name: preheat cache
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt
      - name: update cargo index
        continue-on-error: true
        run: cargo install empty-library
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev
          version: 1.0

      # - name: install dependencies (ubuntu)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev -y
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "libra" # to share across CI builds, so it is not job-id specific
          cache-all-crates: true
          cache-on-failure: true
      - name: cargo release build
        run: cargo b --release