name: test-cache

on:
  push:
    tags:
      - '*'
    branches:
      - 'test-rust-cache-2.6'
jobs:
  types:
    runs-on: ubuntu-20.04
    name: libra-types test
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0

      - name: cache rust
        uses: Swatinem/rust-cache@v2.6.0

      - name: cargo git mtime restore for cargo github dependencies
        uses: chetan/git-restore-mtime-action@v2

      - name: build query
        run: cargo b -p libra-query


