name: test-cache

on:
  push:
    tags:
      - '*'
    branches:
      - 'test-ci'
jobs:


  types:
    runs-on: ubuntu-20.04
    name: libra-types test
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev
          version: 1.0

      - uses: actions/checkout@v3
      # - name: test
      #   uses: actions/cache@v3
      #   with:

      #     path: |
      #       $HOME/.cargo/git
      #       $HOME/.cargo/registry/src/
      #       # $HOME/.cargo/registry/src/**/librocksdb-sys*
      #       # $HOME/.cargo/registry/src/**/jemalloc-sys*
      #       ./target
      #     key: v1-${{ runner.os }}-rust

      - uses: bmwill/rust-cache # Fork of 'Swatinem/rust-cache' which allows caching additional paths
        with:
          path: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
            ~/.cargo/registry/src/**/jemalloc-sys-*

      - name: build query
        run: cargo b -p libra-query


