name: test exit

on:
  push:
    tags:
      - '*'
    branches:
      - 'ci'
jobs:
  exit:
    strategy:
      fail-fast: true
    name: preheat cache
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt
      - name: update cargo index
        continue-on-error: true
        run: |
          cargo install empty-library && exit 0