name: test-cache

on:
  push:
    tags:
      - '*'
    branches:
      - 'test-ci'
jobs:
  types:
    runs-on: ubuntu-20.04
    name: libra-types test
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0
      - uses: actions/checkout@v3
      - uses: bmwill/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
    #https://github.com/rust-lang/cargo/issues/8845
        with:
            path: |
              ~/.cargo/registry/src/**/librocksdb-sys-*
              ~/.cargo/registry/src/**/jemalloc-sys-*

              ~/.cargo/git/checkouts
      # - name: test
      #   uses: actions/cache@v3
      #   with:

      #     path: |
      #       $HOME/.cargo/git
      #       $HOME/.cargo/registry/src/
      #       # $HOME/.cargo/registry/src/**/librocksdb-sys*
      #       # $HOME/.cargo/registry/src/**/jemalloc-sys*
      #       ./target
      #     key: v1-${{ runner.os }}-rust


      - name: build query
        run: cargo b -p libra-query


