name: tools-tests

on:
  push:
    tags:
      - '*'
    branches:
      - 'ci'
jobs:
  ######## WARM UP CACHES ########
  preheat: # Warm up the ca
    uses: ./.github/workflows/preheat.yaml

  ######## TYPES CHECK ########
  types:
    name: libra-types test
    needs: preheat
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt
      - name: update cargo index
        continue-on-error: true
        run: cargo install empty-library
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev
          version: 1.0
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          shared-key: "libra" # to share across CI builds, so it is not job-id specific
          cache-all-crates: true
          cache-on-failure: true

      - name: types test
        working-directory: ./types
        run: cargo t --release
  tools:
    name: libra-tools test
    needs: preheat
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt
      - name: update cargo index
        continue-on-error: true
        run: cargo install empty-library
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential lld pkg-config libclang-dev libwebkit2gtk-4.0-dev libglib2.0-* libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libvips-dev libgmp-dev
          version: 1.0
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          shared-key: "libra" # to share across CI builds, so it is not job-id specific
          cache-all-crates: true
          cache-on-failure: true

      # Check test suite meta tests
      - name: smoke-tests
        working-directory: ./tools/smoke-tests
        run: cargo t --release

      # Tools tests

      - name: genesis
        working-directory: ./tools/genesis
        run: cargo t --release
      - name: query
        working-directory: ./tools/query
        run: cargo t --release
      - name: tower
        working-directory: ./tools/tower
        run: cargo t --release
      - name: txs
        working-directory: ./tools/txs
        run: cargo t --release
      - name: wallet
        working-directory: ./tools/wallet
        run: cargo t --release
